{
 "title": "FastAPI Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Global Traffic & Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n10,\nsum(rate(http_requests_total[5m])) by (method, handler)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Errors/sec",
   "type": "__unconfigured-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Status Class",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(http_requests_total{status=~\"2..\"}[5m]))\n/\nsum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(\n0.50,\nsum(rate(http_request_duration_seconds_bucket[5m]))\nby (le)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n0.95,\nsum(rate(http_request_duration_seconds_bucket[5m]))\nby (le)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n0.99,\nsum(rate(http_request_duration_seconds_bucket[5m]))\nby (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (service) (\n  rate(http_request_duration_seconds_sum[5m])\n)\n/\nsum by (service) (\n  rate(http_request_duration_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(\n0.95,\nsum(rate(http_request_duration_seconds_bucket[5m]))\nby (handler,le,method)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Active DB Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (\n  db_active_connections{state=\"used\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Duration (operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (operation)(\nrate(db_query_duration_seconds_sum[5m])\n)\n/\nsum by (operation)(\nrate(db_query_duration_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by (service) (\n  rate(db_query_duration_seconds_sum[5m])\n)\n/\nsum by (service) (\n  rate(db_query_duration_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(\n0.95,\nsum(rate(db_query_duration_seconds_bucket[5m]))\nby (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}