apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: userservice-secrets
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgAcC2qhPvB2a0N1OAhZtWKtGIcppjVDZ6Nb7V888LsoXppM40FPsm+oNRT2c1qzEV4Kva/AzsGitEJDHZ3i+gFF/B2WM6LkknyA5gMVRz7vCZFPy0So+SQDcAXwZlP/RFZJmHSuLrr5aX4wxF68bgLVZzVeb5d3H53segV+LaXUrQiO02oXd2K2eZa88mg7bE9KIxVxVosVS0OMIpM9s3Ty/dvQX2BWw2y2Xjfq2YHQ+4DGQe9LCtRyC2F/lmVumUrftGR3uVEYkO2EqYrg6XR7kbnQvIp+gUGMk5IUKO3LLoCrPQ9KYVqu1fH3kwM9JtQsnOB57Oi3Mhp+dO43zPAhzj29PJtvcu4zD5Uu3GMMjzu9opFhgAwIxF3Uhy4r4BUYbi4UUG0UyAjCBihUSbMKhQMiYNwDh8PbV8Xj9G19X/aVKQaqP0CJtpA42FdO7PztFSRFSnflU0vYIo0GAkX6zrJzFZXlRVRd5eNCPecYUWfQicdxNkImOg6B19kllEnHAeO3PJEUeSvpt2anC5n3jHMneIL2AoIGKjboN3rewEqNacngdIcFH5uynQXEm5Q47uilANe7gpKY9IWYccwC+uC3veoPePrwXxdkqHblk62kNlRedzIx/oi1yFPKWvx5ZQY3GNwsDnSt1sCo5YY8Xwk5Y4rbCxSOABP2RHHRCr/esLirFRSJhOFpKXLSBq/drq+f91dt9eAYRK8EepnjLOag6KCIkx9MdL5svYrtXfCdw05p9B2OdJeLrDFcxkJ82n0lUsGt3qVQZSLSY4ncRbsiuTN+kce2UprrxE7VSqEHDiONEuGrCQTZwA==
    JWT_SECRET: AgBhCDrQcFtWpenG0k2UEdF4pnPkRNj93zju+XFRH1/elTO/v9upEe6zvR7c9KGTKbJ3SV5JV4IofGyBkjFZmOXXuzDMuWjf6Cm+qvyePyvrEGv1XmgMvu01VwJ+NSllQZNYkTsppV5zdyMfdgUhTfBBlyu3KnFgMD+yCNS5hNTzshGa1nZrk2eKjeN208+mC83WXVxn5OuYuTp6LVz5faMX0dLRNXd11LhZS7iuiVD9QodsP4g+T0yP2sAeR/TLR2y5Ja4egwOiZMyjHhtD/WIRv7v7lMzbBPGUlrbSiyCYihe4JeuxSjPoAUMj1UdnarGxlCDVJ/BPjMlR1mQujPalDlzBjKgFTf90GILdC1Wsu8JVdLR2dSAUXcd0DVoajKnEdZE0mLgygvlcff+emzjRYwSVnYwq9rtytmdRKxzghsw4WYH0bMg3srtKFgiPzArJNTkvDzfQWFk57eUpxKzjdaWYVZJV0MpGQeCqkGH51m8Y4x42NBvNOMqeroKZsDkv48R9tjL4TOlDXcHCw531GfSa2aKK8ekRT2eDmH/PHkiS7fXW4402z++Hv+SLC4ipnFy3n9wJTGikGFhR/nDff5fL+a7wo0N/Hou0GeukFREnOVQGk52IrL2DWGCvzU1rtkkucExs7vpaspiVfHePNvYmmYUqkO4mEcAYRMXxl2tLKf8l5FEYPx/jRri3VyuKnMwUywQSTwXcLHKFDaAC+DnvpMx5YYdQ28DVLAKI8mYG1Ayk78XZfrHYqg==
  template:
    metadata:
      creationTimestamp: null
      name: userservice-secrets
      namespace: apps
    type: Opaque

