apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: userservice-secrets
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgAlgRORISrKhTBcw9FIZzp4CmDm5Mb/QEzIqNdzfJ97ZA59JypNp2rQ4WZn8feh74AoMAlXx5kli/G2Mc9OWADOrXXi/PrZ0w6LXIJHXW5E4Sx2Mn4INN7dCh1asp7ocAIiCSwMFQWbemPQ0mlrNfEf0aLIVEJZU5FrMMon24dvIiY64y0g2GV+a+ypmhwS6uK8SEQax/vzglrVF8BXoYyA5svevhDB6M4dZTfBLVg6ZAZKLEqIaj5CD1wABsFX4nVRvm/6OYUF4NdPtPrSR+15wGG5DQrI/3+i/mdcuLObjjnaVHF1ZfVgek1qzHZ7ZW+mHyZg+GWtLcS1lEHkTCWiIPtqniCPdkusf/j8ObPh6Ib55EumwF0/cy0ZhnMFQnG5xF0NsuXnGbfvShYxohGhI1ZSGVq6+Ycf9eVDiHJCFgAiKBDioH9AHRwx4hEVMR3XbMwZ7Vz6c/Ey8BI3b3t1BVSeO857gj2VCTvG1onZMzoDo2aLKDsjYmZh+RQ2hAAdg3SrFm2MDnGoZtFclqYPB6mZIfiFZJG3wcq8q474U1JORajTdqY8WX+0X0ooT769YhusesiTNSF169yE6bW8m2W6ZVPHmaR9ZdjEHSQVRm0Ej2E2vWkLJTXzB6ds64wIrWRnRPBJFwHkvXskhEwNN43Q8Anmz4U/SNHqvgalTN+9PnBGyPf0Z2dpAMMZlcJi6GaabKAAtVVt9i7riPV0+OLN/+rRDeLUtdFmE1GQ/oo1O/t87WfwDR7dtPdl+2IOSWyQI7N1K2GzvjqjY6IShJOoe5dHO8QAPgSv3imv2YBINmiHyd5hEm+Rww==
    JWT_SECRET: AgCfsv5U1C34iz6DrFmhiuvxDLS345Atyr1QEsh1j0OE0riXDG3oAeXJxsOij8pKaFEZmRGNrr6ocESoK9LAZt9A8ED0+yA7A0HOUsuWThbHGfusmn/An4Wi9cXbXGLYJ2TPFKMx4yDOXMfULJaKFTt5Wq7QKdBxLptwHXeUgsEb4gx0tjVc9DZviNL29SLFRgVe8JOW6lQLtniorS+YkA37epiBOD4y8rMHQ8P5TiZNdonyXh8/muDnCMbO3WVsBqAPgEjOKc9bQXCnnb0c41N36iaZVM/AZtXxXgJJ81F7PwMn+mAtyCmxF+SZz90YhW2aUitZPCJt+emHeorHW2QBLYcAXZ+Zts9mxJMUu0UXrrrkrX+FHMIKvUSpQS0S/Is/xVmiEs4EoHSoaIn7q5EtFwB1LCg5WCTtU5YluVrwSiSAJNxLzRsA9PAIq7JmD9gVf+l8A5LWZIAtQlw3QQ55RM79GceFT9xW6aaoh7AaDmAzgUf24LsTTuKJ8k8HZ+4JT8e46bKzJFMt9dIOhg9GU3T3gRFNDWUn7KsCFeXLsBon0p0P0jesGAp5xCj/amD29UePUfW+9Mr2jNlc5HPu7cGYE2cX88gNoRMwxEZRsCF5dE78JQM3rYG8PxTWomjWyUL+1OycrnuOIF2kLjLUx99mvRzdO7Zz1KjErlBVijlYfsTInajB7yJBntegFbZkEloFaL+N/KXwRAmdR/QMaR4ovnyApRUNB90MziUm+McJy8eSAxgvBbAwKQ==
  template:
    metadata:
      creationTimestamp: null
      name: userservice-secrets
      namespace: apps
    type: Opaque

