apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: object-store-keys
  namespace: observability
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBURQsTRjnMbSZefxJ8xYlZimId34ZG3WCIs3fAVhCM3fbl3qtIhxKwasUOz7saJbIyYYsoe4CRSeODnzTo0gV+Ppi0BbPxXqYDRhAKU/5ScNkQI6Kbn8SXKP1kuONPVFYmOt+mCUxZQ4g54RzlDZ94Fxphi33VVFKsN/AE06lX6Tcqn31k3tbt0qWMhh/wAEdjL2sw6leKlT2TjvwmLjl+wCdV4gl6P8wuCYgDgTDR641//EqEyH37c30qJSGnsKmv3t8VRA/KAWSU6MzSnkZGyRegg1/3jamauByfgqBOtpFqCL6J69vKOLVTfOpGJFp0cfeWVKgq6oMu2KM1XbJMWpe+GcmUR6IOn+wNo60frhuJyYSQ1ipVs8HJfGWg45IdRJ1Jmzay8QsUAl5Qx+huZrCvkAOIIOBchKU/nS23Htjdj9AvrvO/NpjasxzqKo6HMjxJUiDCJzPPjeEeG2vqTSYY6aqDC/+ECuSofo+4QqpPLu4TuuQRgDishmWmfrDjCGSHT5BZu9IPvdfIzF5UNZoVELfWPftaBYsMfhu/skGc/jDdUAU7KEn9yJPg2bPv5R0pN5wZMZACfXyFUzdIf0QHoiPZHZ5fVfb4VtQaD3wvpSVa4xANSzEYDihmDOQzwosZ+RmCiT23WS6qCjikvuAuHmvor9ykiTrGMJWkK+ppkhiZFp2YdS1FvRIXh7e9jomqYy2tdt1+k8XTBSqvCpnS/L0Fgdc91HTUeop5J2aNy8k=
    AWS_SECRET_ACCESS_KEY: AgCeUSSlhcIlYcWjYSldasLlxLVx9rQIkOcpCUrR564cyuGQr/H/RQ9Z/NUEIyQgZ7k6mX5HhOUGTndOnBVrRRuSpRuf2MSbWK9fU3/3Myf4mEmcXAGZFGoRR8BYRmvp0fv2mxfz2TS2hOHb8fdTXVdGkke/PtT5E5upEuIc5QEHJOt19bTDym8ImtCwyo8OIGosYO/YmhzHV7pq9hERCRmPDJu1zMSXZF738pNuWe2/esC34RszeWN620VEhkbOLvV8nutfH+Zb1ZKQ6o0bVyFFGSPVeE/5bDj6Io+X87Lo5ZDt8fZmZzgeUEPeWgWoVD0XWWozmo+dUcAVnAs7xwZiykieO3rslnBLVF7ywqO+M0Gjf25P49v2ndJj3M79pOf1hdGHPejjqR34DvqEb/K0h3ds2YoECMhTQTfPycpC9CbHCaGe/6j/Juctg8wJr5usKRfGdFp8ElOn5grEbsW2Hwhmzz398WHK4UrlTCfX3+KwxfQEB+tSt9CVVcWO/Bfm4d5wKimSk7PYtl3XvNHsvsvzpvZK3yAyWEpczGhYyjFaT7H5oReKtXUB/6fX3NKnAer1FCc2tBA3aYanCXlPke1z/GA9rUlwV4CC9UkuH3S9py6ufoYOLrw9dpv4yvoN8IJk7P1vu8Ni3eXU/d1LdR1Sx9RAHYQzuYrAdAOTTTvcJS7nM5R+itCiXLVjzNKprKT9mvka3okLSypSuhpbNHAtn6qoJJLBzIFY6uNj/W6CG9LF/iqTy8C63CjK1WfY7UI9Bvb4qCGFxWJOgWGO
  template:
    metadata:
      creationTimestamp: null
      name: object-store-keys
      namespace: observability
    type: Opaque

