apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbservice-secrets
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgAlxPUYG6V4TDitWogOEgIHu1p8pPnOJQXLqP96ngYL7vJdsFeCPo6NOtPcnzl0r0gOQQTs8sWi3Q+jU7rA7jnQw3Idjsnm+6K/SnM/6S6kxvuS9iVyEulIK9//Zdoreirz2myEU2M8yiOmiaTxPe6sWvI6XjlzBw7osyiJX/6XU9kjX4R3G0xFfB7XsuDuaqSYg0qTPBHwz6LJNXXpFiD43b5DboHLjHvJZnnGXJCNECJdx9HAQwAV4VD4mqvoO9OnWMWWrrpy+IEv0V7HuTe8QMfojC8fELZdSRcOASwEV8Xotb/9L+Z9SlivYydHzXvTC9TWcRzXX8zfv+FLZyO2l5J0tXMvpRiGiuWhimFH0eDU4qEE0/+I72L2mkpMh8ypTx4bSvBO6yIWqUr1y5osvWfP8BF2gg1ks8mhF7YHzVBFTM/wS2T+ZfMFnwZO6uOCH1Lp80ES7AEuGn+NvhmU6/8JLg8EwzWuT4w1lBajkMhxnLwx9p9ehz97u+HYLVs2Y2TLj3lgzUJZ4SutYlYCJ5X1fxMFYOXtSmkNe9jVd5FGv0WNiZteQZZMZx3rji+kmhJLI7+2JoJenNjS73vIgOxLB3HUSroQlMpfjk0aJDncT8fX9J/gmQDdTPYcQZPWA+lKF/ORg58dVFQqWWNzQ2BODU5tnowo2p28hPOXDh2HkrMpbn828wso172ei0RyvXg7UI/4kruX+kWAgNEvMAVOxdCzVWs29gc49GzPGTK4/uSa0ccE+OFO8VEpEXoQobw1wzgdx/istWPAIZNVBqBHSLsnHFyLLwkuGIbcxjLrXhtt5aA+XTEKHA==
    JWT_SECRET: AgBETMEc4cxnihjRfyjC1B8k5hTKblHRCj4z6g3bKbmkZPzn/aVWc5AivkGzNXK/22Pm3uqxHv3iH+jYi1hc2ipF6KuBRPisf9WfsYwG9thNBxPrKeGx/q/uA8G/ghYN7zbkrULLlQi/MrwwvQ6sBkLFxgLY/sRzCTNcdMwbhgou8W5MGfKAHuLa/kVqrFeU8n3iwXFGvzx3hoViR9BJBtW9yluhS1ShN/KUu+wZMyy8Ptz/o6Kg0Cx7u8mWLC83707v048kMccAW0YfQCvnj7Fe88lI5nshwca3TIcM/sgZCUwKeIpujt84pDNcd59uAD7jyjohRhUJqTF0GOU2eGqKm6ETjYsOZTLgRzIfph4U7rXY3IueWpoSOCPcGVHoE6SK+k1x3zlU15sV0f0m0b9ViIq3/ph32z2oy4d5gPnqh424YJpAgTwOnnMeGz4sLBqnDwB+k32yEpI/Soa5UtlDv0ooEXYtrDycuXCq38GQKTC4x6SpFbmypUcGRgmidhY6w8BmhCcbNGV6/rFD5v16T/BUCiJycTlDt5rjBV3DNTL1qAaKvNMMmrj41bllqjRAUqLXspMnzvMkzY96pzTyYfQR/LupHevEPmNllCa0PoKNRjg2/3wh3QIgNbfK+8obdpkS7rnXNPHpWgk0EmJXvQ39UsS4GvFanSPfrHs5qhmzOQur1IUTIiUwplaE07cys7MPp8ntVl34Cipo9IVP6BSGV0mC6ZsyfwYjL9vx9j90mDP9X6vXWTDkBQ==
  template:
    metadata:
      creationTimestamp: null
      name: dbservice-secrets
      namespace: apps
    type: Opaque

