image:
  repository: ghcr.io/daryoush-safe/db-service
  tag: sha-5829c4be41fb42d51df65a491307d5e868e27499
app:
  port: 8003
existingSecret: dbservice-secrets
env:
  APP_NAME: DBService
  APP_HOST: "0.0.0.0"
  APP_PORT: "8003"
  DEBUG: "false"
  DB_ECHO: "false"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
  PRUNER_BASE_URL: http://pruner.ml.svc.cluster.local:8000
  CORS_ORIGINS: http://localhost:3000
  ROOT_PATH: /db
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy.observability.svc.cluster.local:4317
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: observability
ingress:
  path: /db
  stripPrefix: true
