image:
  repository: ghcr.io/daryoush-safe/db-service
  tag: sha-60300ee8ca4f920cd0d1aa95ca0774b931508bdd
app:
  port: 8003
existingSecret: dbservice-secrets
env:
  APP_NAME: DBService
  APP_HOST: "0.0.0.0"
  APP_PORT: "8003"
  DEBUG: "false"
  DB_ECHO: "false"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
  JWT_ALGORITHM: HS256
  CORS_ORIGINS: http://localhost:3000
  ROOT_PATH: /db
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy.observability.svc.cluster.local:4317
  OTEL_PYTHON_FASTAPI_EXCLUDED_URLS: "healthz,readyz,metrics"
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: observability
ingress:
  path: /db
  stripPrefix: true
