apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chatservice-secrets
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgCoF8TDlqay/+9zZSysb59vtpdJerpSnWYa0qkMRJ5NIy8Sm4lNqTS8GsJxdZv3GdDAiVFPy7PdhUttvLN9bqthBI+JPMdBWUh7TW4NRtoujUJ1REPwaB86JJDrvznzJrcmyxencHXSH9jBXQOO5t4RBXWemBBV+zr9B794pBcOSh1ASpmyyC9x3e1s9QuoAPrEkBKrziZSVHR3ccY8WOei69t1LaTGqsG02U8q3OcBtZjjox7QIPxbCDJpktc4AfNN/im9PjzvzP6Y0Z4z56tn7Il/dDNtZuzC5wa+lNw3LYn+Ds+FBafSKDAOieDGHdRnAQjZ0U4k3UBxj3k4qFe4BibMckOpn9rFzS/BSOPt+1JaRmH44B31jjNQHF+DZm0iSlrFOBnQnQPIlxgqbRwX6ECsoaPeGa0ivBzYffxvr2oqSUKOzfLs0lke2XNZCQH01G1dQ1YF90Z8cIJ6enIilg8876qFY/58V9ASJiyrKGPBe0tkGWewDMnGWzouB42XOgDJ4urVyAO9s56+RfuOta9VEvEZp2kG3tHRk+PbnzWoQD0JyyVRro+cBbpevNUq4my1EGAdCjYpA6fPvlz4guBCT0lQWwTOy2kTA6czZi6rf6GEeohonb5b0F00jqI6fPW8ZpyVevEe7NMbMV6Pxi6Qv6ukGA3sk0NM0WJTwZiOwqhgxxYsWt6P6YtJkM/xakGv+D4/kpsDe92qvdxYYntfdh7qfDgKTwt6vn1fPKR67VGBx/IAxma9DuhonAee6ZZ2XoGJ6vKAJUpwJFaz4bHzmaf/9vp4Q33X3b+gIclZ8hIRWzFfO32k2Zs=
    JWT_SECRET: AgARVy+PHT6v5GFWEoc3I7dXO0iVBo+7zIpNDPthBWmmKGAFltmg5M1a7sWXGD6CDAqvsUiNNS98OLgY8yNe813IJGDuOjSBZyvmOUiSmQyY6tVTt4DbAI+IAkGlkqQf8QF4HWOEO80aWwPMnSKzUh+VQwwjWyN1e/9Mexym7JfG9LwFU6F78kGiVaAL+RfvLSA2STm8Lilpsxx3YZC5MQPCQjmBxl+wClN0IiL5PHc71Qg2DoXRypebD1NrbClJHsyo5/KAm+isSOA6puvsVWGqKEnOXfpzi7stOi0DRsXgNEYMTQd4bZDFfdFPAl9KtaWe/BkSc6172yNFwe86QXrweuXyRPcMWtb6vFbOhzTO97tXpYzW8JLdlO4+zG8MNQHDF/QdqT4JTYPu1Cmn2Mg0zhvJ/9+K5BPMak1KM4Kd9AeFCv3DCF8DvY6aiMZzNAjY/hSCLeH1CmWWaGA13v38KGvz1t8ku5eFbuxsmRaDnU6LbJUaWWzLemU6jOVtTGVnq2lHM/Mcc+E8KJ9DJXJ9A1rCyhJhhl9pOb3+sb5icass4ThOMWhqUFTrRoODXrmopR4YCKzgj2PMn61nDdieeZFIdWEAVR+BSKNw8Vst5RSoDRmtV/iAAz4T6kjoZBA7mxG7cFMuoT6RadoN4+tPxl88MK7CI7Stqy0lCs86c2wdlEPbg1RmXHiAmhA1MaQxGS2O8yfoYXdewtQlTNm1D8DVBbEgDyX3JLLx+AUceW3sazdM442jS1U2xA==
  template:
    metadata:
      creationTimestamp: null
      name: chatservice-secrets
      namespace: apps
    type: Opaque

