apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chatservice-secrets
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgAaf2LwyyVdbjJ+5lqG5/qdF4o53LOQXnCcDnnT3VA0j61w0qpqMp5EyXNgzdhgxQwruiZD3J+a44OqvpoPIuMXwba0GPi7m3YXt909TXcwlzBrpDjRa2ZQHlJ64QDIs32mEVTF1opoaKh76M+NIsyriXaHW8b7bJ/OKGBod4nu/v4ERcbQ/mNRPqgZrE4Hp0RmjyL15SYc2CEPoyQJA8y0R9OE2edttkFfm+ODPQ6Tx03JEIRTuEDyvrpJrrCvZeiQ2PoVIhlBp5RMNRXOKoyctHXpDrz12fqEH5jIaCQs1oo943703+n09wkHjK4UwL2K6q0soD7Qzmhx4YxQTiCY1vc9dtsCsqI0L7MquRparNYYk9iUjHzreCEFv4KVGBFKGzWDXmrnDSZihZWZmGVTKtuFYZ02x9iiHWa49Z1gDxBsQwkRrxpkj41ga4upqjfo35T15BspkivJXHLDbZWhrlCStbiEn/MYiJpQEU0pnDV3xmoRiJeKV0V0vjECc2N34guCL8uXjz1GVkmTYH1nq8XY8oWKY1b2JAgrCStZdr6GE4nVwltn5TqdbdQUjdw7E4T0cHtBJ9LtapRyoLxVIn0WwuU6pO8zqJ5B4aiqnxR21aYJ2UdOmsVed3o55p6xgKj/6xZ/l96Q+NKPnc+JlBSFGyc+tQ8BmqcCDyebh53WCDXaCt2ADrozIRwOiqlR1MRRSx3yFPmLbQY1NIRNQvRDF9BEpvCvFvQR45XOU28zcPFyxHA/qlftD5EF8jOqS2M9pFpKtJ5XxD07mvNycmH2Bc2qbHQVVpSoihyjkGkzd0KBpEQCyYPgs5Y=
    JWT_SECRET: AgB4XNdU7ufbPCj+VLzunzdF2WGnra7LH5qhJ66y1SPS+3LCeNwmRVNnyB2f5V8uU4Hj4nbsOBJLRiFEXMWOGRUouqFzYahnz4VTv28bbR4Cs7eBhIK3F4jWOzFk2i3tilHv6UfbtI6a27Q0hlky1Uzy7ZthGXrWGpyXuJs8jl2Um+hdqOgPYa8UXsrRBVXY68FZq+/mGI1k/k2Lojm2LXYK+CNbdCmZL9DM2loPKJKQXxfVcxz3/zbW1Vell1e4S+zDQ6T6v1HLeXMdTAVejq14xHKpG8NngXoR5lKT4FaLj5lXF4hEAfUAs+QQhGVYizaCzujnh5A86W3wCs78s/emhoEvli+qhb9nN8uTkSyRgdmTJYjvWc2Mv2W6xyens6rcpiA+ZWghBSDzfx5L5lYSmmiRjUcw13VnCxLd3u3xJzg0Y3+NIiLFM+kK8JwpdENiTjWqVP0iuvYoClWuY1xR/qiulSqCmM6REPAq5tDQLnB5P9opwsa6oM39EqM0EROm5XitGnQ93PeNPlwWru2IL1lgXENKYg0A5LMTxSBqzmgZ1R77QpNFt8N+3EgOLjdufS5Y0d7P05EyqB75tOK5Su/rtgmtdesSEn9/MiYfX9EXr5Hbxp0arDnMYSJ8hjzMYqgDfP3flRwSLmD/lw0vg+oh05WD087uNZ9afx+hExrVJQh4mgShvgiAwbuzZR0Rqyj1vsjUYYQIGug8jelrR25nu5NEYA6d+VsEMXD3DL1ZNi79KozS7TZKtg==
  template:
    metadata:
      creationTimestamp: null
      name: chatservice-secrets
      namespace: apps
    type: Opaque

