image:
  repository: ghcr.io/daryoush-safe/chat-service
  tag: sha-60300ee8ca4f920cd0d1aa95ca0774b931508bdd
app:
  port: 8004
existingSecret: chatservice-secrets
env:
  APP_NAME: ChatService
  APP_HOST: "0.0.0.0"
  APP_PORT: "8004"
  DEBUG: "false"
  DB_ECHO: "false"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
  JWT_ALGORITHM: HS256
  CORS_ORIGINS: http://localhost:3000
  ROOT_PATH: /chat
  KAFKA_BOOTSTRAP_SERVERS: kafka-kafka-bootstrap.data.svc.cluster.local:9092
  DBSERVICE_URL: http://dbservice.apps.svc.cluster.local
  DBSERVICE_TIMEOUT: "10.0"
  MLSERVICE_URL: http://10.179.201.1:8080
  MLSERVICE_STREAM_PATH: /stream-query
  MLSERVICE_TIMEOUT: "120.0"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy.observability.svc.cluster.local:4317
  OTEL_PYTHON_FASTAPI_EXCLUDED_URLS: "healthz,readyz,metrics"
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: observability
ingress:
  path: /chat
  stripPrefix: true
