alloy:
  configMap:
    create: false
    name: alloy-config
    key: "."

  clustering:
    enabled: true

  mounts:
    varlog: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

controller:
  type: daemonset
  tolerations:
    - operator: Exists
