apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/daryoush-safe/platform.git
        revision: master
        files:
          - path: "apps/values/*.yaml"
  template:
    metadata:
      name: '{{ trimSuffix ".yaml" .path.filename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/daryoush-safe/platform.git
        targetRevision: master
        path: charts/microservice
        helm:
          valueFiles:
            - ../../apps/values/{{ .path.filename }}
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
