image:
  repository: ghcr.io/daryoush-safe/subscription-service
  tag: sha-5829c4be41fb42d51df65a491307d5e868e27499
app:
  port: 8001
existingSecret: subscriptionservice-secrets
env:
  APP_NAME: SubscriptionService
  APP_HOST: "0.0.0.0"
  APP_PORT: "8001"
  KAFKA_BOOTSTRAP_SERVERS: kafka-kafka-bootstrap.data.svc.cluster.local:9092
  DEBUG: "false"
  DB_ECHO: "false"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
  JWT_ALGORITHM: HS256
  STRIPE_SUCCESS_URL: http://localhost:3000/success
  STRIPE_CANCEL_URL: http://localhost:3000/cancel
  CORS_ORIGINS: http://localhost:3000
  ROOT_PATH: /subscription
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy.observability.svc.cluster.local:4317
  OTEL_PYTHON_FASTAPI_EXCLUDED_URLS: "healthz,readyz,metrics"
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: observability
ingress:
  path: /subscription
  stripPrefix: true
