apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-postgres-exporter
  namespace: observability
spec:
  encryptedData:
    password: AgBJ9wug2QfW/INLWCudKUSxBddp9/EmOGw6XxAKwaZ4RrU82GHB/TbYeFNPYhZxoJ2q1514FEN25vX7v/v6upbdPgz8LHUlO75jNpwiVeF5+hZUv2x69/Pv5QoJ7KTaajZH/fO0Lw0wZtzl4qGL4WXr17cJ4lNDcv5O6p4FoDsmnQb4mdoZ1kP4r0tscRDB5bSsME6LESWMykON/39sL5Y+6D/8+77eT8inUNJ7uEsGYiyOc8AYVCF3y/5xC2yyZ/JErGsS4j+U5Uv/EM3L7blRQ0OhBBYWJFDeRSNt2w5ZeKBJmaW22r7ATLscbYncgxJ1NTgL1+qGhMhlZV/QrmwS4pn8Z6iAiPTlFugekLKHO3c/w4orIqXsU7ULWasReAiNgOUAtTBHDmXjafNcbY24I80oGyyAs5Vj5pW3Je2xP0ZUjIczUMJJQXOsNMk1fEOF1wW8P3/aHtCSU3erO8d3KQuw17nZh3zZfZgAroqKPTjdyMRSJRkpJC1pC5oatEW4euv35igwEQMxtiAhwSPepBAIRvHPGgzNuxADDrUnbsyPc7rchKIh7YPpnMTyyIeD4PFS+1Vng/tkS2tBUz2IakcR+Fu6QhGLFquuR9tcULOT23OM7x5JVNKIbjUHtkP2V9EGRFfNOk3EDMXUz+9NHKCn/uREnO+xaZCHi3zU64bBxDPmekwOJ6B2V0qQRVzTJ174B0lq1w==
  template:
    metadata:
      creationTimestamp: null
      name: secret-postgres-exporter
      namespace: observability
    type: Opaque

