serviceMonitor:
  enabled: true
  namespace: observability
  interval: 30s
  labels:
    release: observability

config:
  datasource:
    host: postgres.data.svc.cluster.local
    port: "5432"
    user: postgres
    database: postgres
    
    passwordSecret:
      name: secret-postgres-exporter
      key: password
