apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbservice-secrets
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgBlfG21JM5aOAA37qk9sRdkfi/TRncxmy+YqMmq1uAiUo69VG5UaQZ+mpuzH7rJDde3o0Pksyun9ifkJhtb3lKtHEeRhVXyKL6oIDwMcOOrBn6onaWMWPUVWhUzNq1IPAjx40tvZbYlwisnNFeNTNElFqsDdwzZNQID11YzvHA553svdPulLWoMmrcQa2E5u47/zYI67k9xqPMoCEJQIw8z5PPcHHe8N8JUPkoc9PhuRb1YQxqIAA86XQVv2hnIwh9OfIYj+TmasXz08jf0OLi8/apry0tmD5Z0nV44b0RZINMxIvjYOdpPF7GC8ilXekp9Td34HGo8xlhm7aJwu9E2X/bUE/BC4NsP8flTnA3Ak4+FN93vAkUCMWNkJoDXv9TZ+mLuK8RNVSZTEZceY2X22H762sfXT03i0HurV373P3Z4lay0AFhAxOsUhqi+Jhriz/QDiWnol/rzffpIvkLc3SKqgO3lsKeOnNBlvB1Rm7ViIN/+U+cPS80DvEyuxm+zI2FaMCkbu+agpOqMnTROCkkgp6SIPiClYuWkjgsj+1E0xrIpYs8aw/muySBHMnSXqXWB9wjea+RmI9VZxHmPRcmqj6XmT9D/FZoRxjswrVDd4pggpFGTjIpCe6yLycMVdNMza8y5/JwFUG3RgV2LZBgspRsRDP9EKq7W8n/Y06OyncnsI+G/eGz8WrAktDFbGqtS9QjoarrRMi1qANFaUp2aVN6QV5B/hrnKbtMacik6iSOuSWL03myF2IyiWgUeBB9YIFetv39k8kzzC9geBZAptRLPNjYyu5dVVEMdw9LgG6I3BeLrufTRZw==
    JWT_SECRET: AgAMExKrUN/Rakm929DMZrt354w9vq0xN3tRYuTyXu+in3Z5s4hG1aWzAHgdXaqrtxi4f7qq5Q5TCX6sAyvkvDoWmmVlxjx7rTqP3UbwaqdXMSAZdwbJ3W2ij2s+lsRWS2AB5Em0X9px9DoB4WL+ypO3S67tt16QgH8SFwOzuAZr/+o9vrs/kbG6X0QgNwPTm8wEmzV5uUsX4/FocofjmLXZdJLcTL/3FC7fAtczNkEKgVv/umYCVTo75vrLP0MeB1K3BffU8qffoYqouNNq00ZCb+/5ab5Oedh6eYWGIjdONCqOSWBfDfushbn+8P/mwWyXA9zdzicGVt7hNg50g/Bt4HqePr0TxSuRJmrvDAkWXSdlcFFS7S1efundIAv9N6bVIL6+wYh9S2MHhpqDhr1yEruvIRcb2/Tk4IO//3QCAa/ecdglhdYe+9f7Dr3g8lku7tzIGlTeyPToO7d52PItwd7Gn+JmmBKt3lahjNkTH57IK7lWIWDMTVuvlfpxNKdnFB58bKn9RG9XtundCR3/KkYegvTJRGgFeUKaT8Xkxb8vltCtQPHl3C81YE8s1/w4nflWcS4w1Q/H3KKm+20E5dXHaxmBac8ldtU/k3TIq0H5UU53p9JXndgV4dwdjCqQkXOupqMQA2mJFXsUBuFboYZJFFJAftykPBlMo1jKmpa3M/M8C+O8PjGJRsTHaUavYeTQtiJ1meTJtVEkJjjQ4bytMBNZLEpCYaYCywIJdaiU+Y1S+HirhNk/Sg==
  template:
    metadata:
      creationTimestamp: null
      name: dbservice-secrets
      namespace: apps
    type: Opaque

