kafkaServer:
  - kafka-kafka-bootstrap.data.svc.cluster.local:9092

kafkaBrokerVersion: "4.1.2"

prometheus:
  serviceMonitor:
    enabled: true
    namespace: observability
    interval: 30s
    additionalLabels:
      release: observability

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

kafkaLabels:
  cluster: "kafka"
  namespace: "data"