apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gmail-auth
  namespace: observability
spec:
  encryptedData:
    password: AgAcygdu3D+L4e6Mgr4A35yJCeF/U8+f70DuPl78TShQl1326EQ/2us4z7WDWmd9TtPnrmYKW4blDKbJqZ9pWfGBz/9jsRyXcESBsdujz0QrQI1H1gtGHa0IHWSs+IWrCLuwdtZvG6mG/dC+rQ7LjraZvxU307voq1i+TnJpOje29BlIfRMGPm1pP4WANlpUtfwFpJqSn+vmWKupYNKfha9KAIFYvySspl2dBaJpfrFot3LUSFqp8+gXstjClH8D2PUn4aUk8s1aUqdx5W3C0Ob/wbaC5mG1RPWw+llVT5SG5JOaS6B0THyQbTUF8GmbmOOm89D9/orUtzeHXlOgwK35w0fVynqCxYwi7ufZL5aaqNl0YRYZwoCsCCsb4OS2cH8JvtibB0AsQa6om/E3KHmLpzT+ICxZmkHGdThfskDC3FDVkUPY69wruFUrp96vnF+N6ero/Dg9OO2hzO0zfjnRoIscaMJkUvOCm269cPIllsV7jJL3dpuGhTN+FT4RjmNPviRFedR2Zem/17iSVNV8BxzcQO/h+VPBLrXRJbJinhnyxvsjbCeeGgZ6V6UhHBEXEpWPzMEaecwvBLA7BSDrjXBUYcadIz30N+WjaKtMxUObvArg7yu8epvFEuMi+tAX666tu/P7/I90U9UQRp7i/6d9k8F5ZglMALpqrtNtLUFkvC7KVuhGAtflH9JM1torix/4phgzJFKjwjA00WL4
  template:
    metadata:
      creationTimestamp: null
      name: gmail-auth
      namespace: observability
    type: Opaque

